### PR TITLE
Add the milestone delivery for Phase 2 of Fruzhin Java Host

### PR DESCRIPTION
**Pull request by hgergov**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/pioneersprize/Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the account provided in the application.

Link to the application pull request: https://github.com/pioneersprize/Polkadot-Pioneers-Prize/pull/12

### CODE REVIEW

**Comment by bhargavbh** [comment]
Hi Hristo, i will be evaluating this delivery. At first trial, i realised the runtime is not loading in full-node mode. The warp sync succeeds and reaches all the way up to previous epoch of the latest block. This is as expected, because the node needs info/parameters from the babe pallets to sync up to the latest block. Please let me know once this is fixed

**Comment by hgergov** [comment]
> Hi Hristo, i will be evaluating this delivery. At first trial, i realised the runtime is not loading in full-node mode. The warp sync succeeds and reaches all the way up to previous epoch of the latest block. This is as expected, because the node needs info/parameters from the babe pallets to sync up to the latest block. Please let me know once this is fixed

Hey @bhargavbh and apologies for the late response,

Thanks for raising it. We are looking into it and will follow-up in the next couple of days.

**Comment by vikinatora** [comment]
@bhargavbh The runtime building issue is resolved (please pull changes in `dev` branch). The node can start, warp sync and build runtime. However we currently lack the ability to continue with full node sync after that point. This is going to be implemented in Phase 3 - Milestone 4 - Task 8 Improve syncing strategy.

We support starting syncing from block 0 and going one by one. This can be done by running the node with `--node-mode full --db-recreate --sync-mode full`.

**Comment by bhargavbh** [comment]
Hi @vikinatora thanks for your response. i pulled the latest on dev.  IIUC, the node can't start full-sync for the current epoch after warp-syncing until the last epoch? As a suggestion, Ph3-M4-task8 is quite vague and may be issues like this should be concretely mentioned. 

Another issue i have faced is when running the node in full mode and full sync on westend. The sync stops after 594 block. is this because of discrepancy in storage root calculation?
Screenshot 2024-05-10 at 08 56 44

**Comment by vikinatora** [comment]
Hey @bhargavbh, thanks for the fast reply. The description of Ph3-M4-task8 will be adjusted to better reflect our intentions! As for the sync stopping on block 594, that should have been resolved for a few weeks now. I just ran Fruzhin in this mode you mentioned and surpassed the problematic block. Are you sure you've rebuilt the code after pulling the changes?

**Comment by bhargavbh** [comment]
my bad, i had found this issue last week and shared assuming it still persisted. thanks

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
